/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BubbleImageRenderer: (typeof import('./src/components/BubbleImageRenderer.vue'))['default']
    Button: (typeof import('./src/components/Button.vue'))['default']
    GenUISwitch: (typeof import('./src/components/GenUISwitch.vue'))['default']
    ModelSwitch: (typeof import('./src/components/ModelSwitch.vue'))['default']
    PluginToggleButton: (typeof import('./src/components/PluginToggleButton.vue'))['default']
    QrCodeScan: (typeof import('./src/components/QrCodeScan.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    TinyRobotChat: (typeof import('./src/components/TinyRobotChat.vue'))['default']
    TokenUsage: (typeof import('./src/components/TokenUsage.vue'))['default']
    VanIcon: (typeof import('vant/es'))['Icon']
  }
}
