/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    InventoryModal: typeof import('./src/components/InventoryModal.vue')['default']
    PriceProtectionModal: typeof import('./src/components/PriceProtectionModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanIcon: typeof import('vant/es')['Icon']
  }
}
