/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TinyButton: typeof import('@opentiny/vue-button')['default']
    TinyFormItem: typeof import('@opentiny/vue-form-item')['default']
    TinyInput: typeof import('@opentiny/vue-input')['default']
    TinyModal: typeof import('@opentiny/vue-modal')['default']
    TinyTabItem: typeof import('@opentiny/vue-tab-item')['default']
    TinyTabs: typeof import('@opentiny/vue-tabs')['default']
    TinyTree: typeof import('@opentiny/vue-tree')['default']
    VanIcon: typeof import('vant/es')['Icon']
  }
}
